apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: k8sargo-cluster
  namespace: tkgs-lab
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.98.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "vds-cloud.vmw"
  topology:
    class: tanzukubernetescluster
    version: v1.23.8---vmware.2-tkg.2-zshippable
    #describe the cluster control plane
    controlPlane:
      #number of control plane nodes; integer 1 or 3
      replicas: 1
    #describe the cluster worker nodes
    workers:
      #specifies parameters for a set of worker nodes in the topology
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 1
    variables:
      #virtual machine class type and size for cluster nodes
      - name: vmClass
        value: best-effort-large
      #persistent storage class for cluster nodes
      - name: storageClass
        value: goldsp
      - name: defaultStorageClass
        value: goldsp

