apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: argo-ns-full-argocdsa
  namespace: tkgs-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-ns-full
subjects:
- kind: ServiceAccount
  name: argocdsa
  namespace: tkgs-lab
